[shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Bold Italic"
